name: Deploy GVF Theme to HubSpot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Verify environment variables
        run: |
          if [ -z "${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}" ]; then
            echo "Error: HUBSPOT_PERSONAL_ACCESS_KEY is missing"
            exit 1
          fi
          if [ -z "${{ secrets.HUBSPOT_ACCOUNT_ID }}" ]; then
            echo "Error: HUBSPOT_ACCOUNT_ID is missing"
            exit 1
          fi

      - name: Create HubSpot config file
        run: |
          cat <<EOF > hubspot.config.yml
defaultPortal: production
portals:
  - name: production
    portalId: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
    personalAccessKey: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
EOF

      - name: Upload Theme to HubSpot
        run: |
          echo "Starting upload to HubSpot..."
          hs upload hs-theme hs-theme --notify --skip-unchanged-files

      - name: Notify Slack on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "🚨 GVF Website Theme deployment FAILED on branch *${{ github.ref }}*!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
