name: Deploy GVF Theme to HubSpot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HubSpot CLI
        run: npm install -g @hubspot/cli

      - name: Authenticate HubSpot
        run: hs auth personalaccesskey ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}

      - name: Upload Theme
        run: hs upload hs-theme hs-theme
